version: 2
jobs:
  build:
    docker:
      - image: node:8.0

    working_directory: ~/my-project

    steps:
      - run:
          name: "Checking Versions"
          command: |
            node --version
            npm --version
      - checkout
      - run:
          name: "NPM Install"
          command: |
            npm install
      - run:
          name: "Running Tests"
          command: |
            npm run test